KerasJson: encoder_4x4_norm_d16_10b3.json
KerasH5:   encoder_4x4_norm_d16_10b3.hdf5
InputData: verify_input.dat
OutputPredictions: verify_output.dat
OutputDir: keras_econ_4x4_d16
ProjectName: econ_4x4_d16
XilinxPart: xcku115-flvb2104-2-i
ClockPeriod: 5
Backend: Vivado

IOType: io_parallel # options: io_serial/io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<18,8>
    ReuseFactor: 1
    Strategy: Resource
#  LayerType:
#    Dense:
#      ReuseFactor: 2
#      Strategy: Resource
#      Compression: True
